name: multithread_downloads
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shelf: ^1.4.2
  shelf_static: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.multithread_downloads
        pluginClass: MultithreadDownloadsPlugin
      ios:
        pluginClass: MultithreadDownloadsPlugin
